<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find rm_description)/urdf/common/omni_wheel.urdf.xacro"/>

    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="chassis_radius" value="0.208"/>
    <xacro:property name="wheel_offset_z" value="0.0"/>

    <xacro:macro name="chassis">

        <link name="base_link">
            <inertial>
                <mass value="8.472226"/>
                <origin xyz="0.009872  0.010973  0.001286"/>
                <inertia ixx="1.131e-1" ixy="-4.480e-4" ixz="-9.581e-3" iyy="1.473e-1"
                         iyz="3.352e-3" izz="2.048e-1"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/standard/base.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.580 0.500 0.050"/>
                </geometry>
            </collision>
        </link>

        <xacro:omni_wheel prefix="left_front" connected_to="base_link"
                          wheel_x_offset="${chassis_radius/sqrt(2)}" wheel_y_offset="${chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${3*pi/4}"
        />
        <xacro:omni_wheel prefix="right_front" connected_to="base_link"
                          wheel_x_offset="${chassis_radius/sqrt(2)}" wheel_y_offset="${-chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${pi/4}"
        />
        <xacro:omni_wheel prefix="left_back" connected_to="base_link"
                          wheel_x_offset="${-chassis_radius/sqrt(2)}" wheel_y_offset="${chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${-3*pi/4}"
        />
        <xacro:omni_wheel prefix="right_back" connected_to="base_link"
                          wheel_x_offset="${-chassis_radius/sqrt(2)}" wheel_y_offset="${-chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${-pi/4}"
        />
        <xacro:wheel_transmission prefix="left_front" mechanical_reduction="-19.2032"/>
        <xacro:wheel_transmission prefix="right_front" mechanical_reduction="-19.2032"/>
        <xacro:wheel_transmission prefix="left_back" mechanical_reduction="-19.2032"/>
        <xacro:wheel_transmission prefix="right_back" mechanical_reduction="-19.2032"/>

    </xacro:macro>

</robot>
